Gestao_Financeira/Gestao_Financeira/Areas/Admin/Controllers/DashboardController.cs
using Gestao_Financeira.Helpers;
using System.Web.Mvc;

namespace Gestao_Financeira.Areas.Admin.Controllers
{
    [Permissoes(Roles = "Administrador")]
    public class DashboardController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Gestao_Financeira/Gestao_Financeira/Areas/User/Controllers/DashBoardController.cs
using Gestao_Financeira.Helpers;
using Gestao_Financeira.Models;
using Gestao_Financeira.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Gestao_Financeira.Areas.User.Controllers
{
    [Permissoes(Roles = "Usuario")]
    public class DashboardController : Controller
    {
        private readonly Financeiro _financeiro;

        public DashboardController()
        {
            _financeiro = new Financeiro();
        }

        public ActionResult Index()
        {
            try
            {
                if(Account.UsuarioId == Guid.Empty)
                    return RedirectToAction("Index", "Home");

                var listaDeAnos = _financeiro.BuscarTodos(Account.UsuarioId).GroupBy(x => x.DataLancamento.Year).OrderBy(x => x.Key).ToList();

                ViewBag.SelectAnos = new SelectList(listaDeAnos, "Key", "Key");
                ViewBag.DataInicial = listaDeAnos.Count() != 0 ? listaDeAnos.FirstOrDefault().Key : DateTime.UtcNow.Year;
                return View(_financeiro.BuscarTodosPorAnoMes(Account.UsuarioId, DateTime.UtcNow.Year, null));
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home");
            }
        }

         public ActionResult CarregarPainelPorAno(int ano)
        {
            return PartialView("_Painel", _financeiro.BuscarTodosPorAnoMes(Account.UsuarioId, ano, null));
        }

        public JsonResult GraficoGeralPorAno()
        {
            var entrada = new List<decimal>();
            var saida = new List<decimal>();
            var saldo = new List<decimal>();
            var result = _financeiro.BuscarTodos(Account.UsuarioId).GroupBy(x => x.DataLancamento.Year).OrderBy(x => x.Key).ToList();
            foreach (var item in result)
            {
                entrada.Add(item.Where(x => x.TipoFinanceiro == TipoFinanceiro.Entrada).Sum(x => x.Valor));
                saida.Add(item.Where(x => x.TipoFinanceiro == TipoFinanceiro.Saida).Sum(x => x.Valor));
                saldo.Add(item.Where(x => x.TipoFinanceiro == TipoFinanceiro.Entrada).Sum(x => x.Valor) - item.Where(x => x.TipoFinanceiro == TipoFinanceiro.Saida).Sum(x => x.Valor));
            }
            var list = new[] {
                    new { name = "Saldo" , data = saldo },
                    new { name = "Saída" , data = saida },
                    new { name = "Entrada" , data = entrada }
            };
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GraficoGeralPorMes(int ano = 0)
        {
            ano = ano != 0 ? ano : DateTime.UtcNow.Year;
            var entrada = new List<decimal>();
            var saida = new List<decimal>();
            var saldo = new List<decimal>();
            var key = new List<int>();
            var financeiros = _financeiro.BuscarTodosPorAnoMes(Account.UsuarioId, ano, null).GroupBy(x => x.DataLancamento.Year).OrderBy(x => x.Key).ToList();
            foreach (var itens in financeiros)
            {
                var result = itens.GroupBy(x => x.DataLancamento.Month).ToList();
                VerificarMesNulo(result, entrada, saida, saldo);
            }
            var list = new[] {
                    new { name = "Saldo" , data = saldo },
                    new { name = "Saída" , data = saida },
                    new { name = "Entrada" , data = entrada }
            };
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        private void VerificarMesNulo(List<IGrouping<int, Financeiro>> result, List<decimal> entrada, List<decimal> saida, List<decimal> saldo)
        {
            for (int i = 1; i <= 12; i++)
            {
                if (result.Any(x => x.Key == i))
                {
                    foreach (var item in result.Where(x => x.Key == i))
                    {
                        entrada.Add(item.Where(x => x.TipoFinanceiro == TipoFinanceiro.Entrada).Sum(x => x.Valor));
                        saida.Add(item.Where(x => x.TipoFinanceiro == TipoFinanceiro.Saida).Sum(x => x.Valor));
                        saldo.Add(item.Where(x => x.TipoFinanceiro == TipoFinanceiro.Entrada).Sum(x => x.Valor) - item.Where(x => x.TipoFinanceiro == TipoFinanceiro.Saida).Sum(x => x.Valor));
                    }
                }
                else
                {
                    entrada.Add(0);
                    saida.Add(0);
                    saldo.Add(0);
                }
            }
        }

        public JsonResult GraficoPizzaSaida(int mes = 0, int ano = 0)
        {
            ano = ano != 0 ? ano : DateTime.UtcNow.Year;
            mes = mes != 0 ? mes : DateTime.UtcNow.Month;
            var result = _financeiro.BuscarTodosPorAnoMes(Account.UsuarioId, ano, mes).Where(x => x.TipoFinanceiro == TipoFinanceiro.Saida).ToList().GroupBy(x => x.Categoria.Nome).Select(x => new
            {
                name = x.FirstOrDefault().Categoria.Nome,
                y = x.Sum(c => c.Valor)
            });

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GraficoPizzaEntrada(int mes = 0, int ano = 0)
        {
            ano = ano != 0 ? ano : DateTime.UtcNow.Year;
            mes = mes != 0 ? mes : DateTime.UtcNow.Month;
            var result = _financeiro.BuscarTodosPorAnoMes(Account.UsuarioId, ano, mes).Where(x => x.TipoFinanceiro == TipoFinanceiro.Entrada).ToList().GroupBy(x => x.Categoria.Nome).Select(x => new
            {
                name = x.FirstOrDefault().Categoria.Nome,
                y = x.Sum(c => c.Valor)
            });

            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

Gestao_Financeira/Gestao_Financeira/Areas/User/Views/Dashboard/Index.cshtml
@using Gestao_Financeira.Utils
@model IEnumerable<Gestao_Financeira.Models.Financeiro>

@{
    ViewBag.Title = "Index";
    var mesAtual = DateTime.Now.Month;
}
<div class="col-md-12">
    <div class="float-right">
        <b id="ano-d">Ano: </b>
        <select class="form-control text-center anodefinido" id="KeyAno">
            <option value="" disabled selected hidden>@DateTime.UtcNow.Year</option>
            @foreach (var item in (SelectList)ViewBag.SelectAnos)
            {
                <option value="@item.Value">@item.Text</option>
            }
        </select>
    </div>
    <div class="float-right mr-3">
        <b id="mes-d">Mês: </b>
        <select class="form-control text-center mesdefinido" id="KeyMes">
            <option value="" disabled selected hidden>@DateTime.UtcNow.Month.GetSelectMonth()</option>
            <option value="1">Jan</option>
            <option value="2">Fev</option>
            <option value="3">Mar</option>
            <option value="4">Abr</option>
            <option value="5">Mai</option>
            <option value="6">Jun</option>
            <option value="7">Jul</option>
            <option value="8">Ago</option>
            <option value="9">Set</option>
            <option value="10">Out</option>
            <option value="11">Nov</option>
            <option value="12">Dez</option>
        </select>
    </div>
</div>
<div class="col-md-12 pr-0 pl-0">
    <div class="row pr-3 pl-3" id="div-painel" data-url="@Url.Action("CarregarPainelPorAno", "Dashboard", new { area = "User"})">
        @Html.Partial("_Painel", Model)
    </div>
</div>
<div class="col-md-6 pr-0">
    <div class="mb-2 grafico" id="graficogeralporano" data-anoinicio="@ViewBag.DataInicial" data-url="@Url.Action("GraficoGeralPorAno", "Dashboard", new { area = "User"})"></div>
</div>
<div class="col-md-6 pr-0">
    <div class="mb-2 grafico" id="graficogeralpormes" data-url="@Url.Action("GraficoGeralPorMes", "Dashboard", new { area = "User"})"></div>
</div>
<div class="col-md-6 pr-0">
    <div class="mb-2 grafico-pizza" id="graficopizzaentrada" data-mes="@mesAtual" data-url="@Url.Action("GraficoPizzaEntrada", "Dashboard", new { area = "User"})"></div>
</div>
<div class="col-md-6 pr-0">
    <div class="grafico-pizza" id="graficopizzasaida" data-mes="@mesAtual" data-url="@Url.Action("GraficoPizzaSaida", "Dashboard", new { area = "User"})"></div>
</div>

@section scripts{
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/series-label.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>

    @Scripts.Render("~/bundles/grafico-geral-por-ano")
    @Scripts.Render("~/bundles/grafico-geral-por-mes")
    @Scripts.Render("~/bundles/grafico-pizza-entrada")
    @Scripts.Render("~/bundles/grafico-pizza-saida")
    @Scripts.Render("~/bundles/select-ano-definido")
    @Scripts.Render("~/bundles/select-mes-definido")
}

Gestao_Financeira/Gestao_Financeira/Areas/User/Views/Dashboard/_Painel.cshtml
@model IEnumerable<Gestao_Financeira.Models.Financeiro>
@using Gestao_Financeira.Models
@{
    var entrada = Model.Where(x => x.TipoFinanceiro == TipoFinanceiro.Entrada).Sum(x => x.Valor);
    var saida = Model.Where(x => x.TipoFinanceiro == TipoFinanceiro.Saida).Sum(x => x.Valor);
    var saldo = entrada - saida;
}

<div class="col-md-4 pr-0">
    <div class="card card-stats mb-2 mt-3">
        <div class="card-header card-header-success card-header-icon">
            <div class="card-icon">
                <i class="material-icons">attach_money</i>
            </div>
            <p class="card-category">Entrada</p>
            <h4 class="card-title money">@entrada</h4>
        </div>
    </div>
</div>
<div class="col-md-4 pr-0">
    <div class="card card-stats mb-2 mt-3">
        <div class="card-header card-header-info card-header-icon">
            <div class="card-icon">
                <i class="material-icons">attach_money</i>
            </div>
            <p class="card-category">Saldo</p>
            @if (saldo < 0)
            {
                <h4 class="card-title" style="color: #fd7d7d">-<b class="money">@saldo</b></h4>
            }
            else
            {
                <h4 class="card-title money">@saldo</h4>
            }
        </div>
    </div>
</div>
<div class="col-md-4 pr-0">
    <div class="card card-stats pr-0 mb-2 mt-3">
        <div class="card-header card-header-danger card-header-icon">
            <div class="card-icon">
                <i class="material-icons">attach_money</i>
            </div>
            <p class="card-category">Saída</p>
            <h4 class="card-title money">@saida</h4>
        </div>
    </div>
</div>