Gestao_Financeira/Gestao_Financeira/Models/Usuario.cs
using Gestao_Financeira.Repository;
using Gestao_Financeira.Utils;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Gestao_Financeira.Models
{
    public class Usuario
    {
        #region Atributos
        public Guid UsuarioId { get; set; }
        [Required]
        public string Nome { get; set; }
        [Required]
        public string Login { get; set; }
        [Required]
        public string Senha { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string Email { get; set; }
        public bool EmailConfirmado { get; set; } = false;
        public TipoUsuario TipoUsuario { get; set; }
        public bool Ativo { get; set; } = true;
        public bool Excluido { get; set; } = false;
        public DateTime? DataAlteracao { get; set; }
        public DateTime DataRegistro { get; set; } = DateTime.UtcNow;
        #endregion

        #region Bidirecional
        public ICollection<Categoria> Categorias { get; set; }
        public ICollection<Financeiro> Financeiros { get; set; }
        public ICollection<Log> Logs { get; set; }
        #endregion

        #region Crud
        UsuarioRepositorio _usuarioRepositorio = new UsuarioRepositorio();
        public void Adicionar(Usuario usuario) => _usuarioRepositorio.Adicionar(usuario, $"Adicionado o usuário {usuario.Nome} com o perfil {usuario.TipoUsuario.GetDisplayName()}");
        public void Atualizar(Usuario usuario) => _usuarioRepositorio.Atualizar(usuario, $"Atualizado o usuário {usuario.Nome} com o perfil {usuario.TipoUsuario.GetDisplayName()}");
        public void Excluir(Usuario usuario) => _usuarioRepositorio.Excluir(usuario, $"Excluido o usuário {usuario.Nome} com o perfil {usuario.TipoUsuario.GetDisplayName()}");
        public void Cadastro(Usuario usuario) => _usuarioRepositorio.Cadastro(usuario, $"Usuário {usuario.Nome} se cadastrou no dia {usuario.DataRegistro}");
        public Usuario BuscarPorId(Guid usuarioId) => _usuarioRepositorio.BuscarPorId(usuarioId);
        public Usuario BuscarPorLogin(string login) => _usuarioRepositorio.BuscarPorLogin(login);
        public IEnumerable<Usuario> BuscarTodos() => _usuarioRepositorio.BuscarTodos();
        public IEnumerable<Usuario> BuscarTodosPorFiltro(string textoDigitado) => _usuarioRepositorio.BuscarTodosPorFiltro(textoDigitado);

        #endregion

        #region Métodos
        public void AtivarOuDesativar()
        {
            Ativo = !Ativo;
            DataAlteracao = DateTime.UtcNow;
        }

        public void CriarUsuario(string senha)
        {
            TipoUsuario = TipoUsuario.Usuario;
            Senha = Hash.GerarHash(senha);
        }

        public void AlterarUsuario(Usuario usuario)
        {
            Nome = usuario.Nome;
            Login = usuario.Login;
            DataAlteracao = DateTime.UtcNow;
            if (usuario.Senha != null)
                Senha = Hash.GerarHash(usuario.Senha);
        }

        public void ExcluirUsuario()
        {
            DataAlteracao = DateTime.UtcNow;
            Excluido = true;
        }
        #endregion
    }
}

Gestao_Financeira/Gestao_Financeira/Areas/Admin/Controllers/UsuarioController.cs
using PagedList;
using Gestao_Financeira.Helpers;
using Gestao_Financeira.Models;
using Gestao_Financeira.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Gestao_Financeira.Areas.Admin.Controllers
{
    [Permissoes(Roles = "Administrador")]
    public class UsuarioController : Controller
    {

        private readonly Usuario _usuario;

        public UsuarioController()
        {
            _usuario = new Usuario();
        }

        public ActionResult Index(int pagina = 1)
        {
            try
            {
                if (Account.UsuarioId == Guid.Empty)
                    return RedirectToAction("Index", "Home");

                TempData["Pagina"] = pagina;
                int itensPorPagina = 5;
                var usuarios = _usuario.BuscarTodos().Where(x => !x.Excluido).ToList();
                var lista = new List<Usuario>();
                lista.AddRange(usuarios);
                return View(lista.ToPagedList(pagina, itensPorPagina));
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult Adicionar(Usuario usuario)
        {
            if (!ModelState.IsValid) return RedirectToAction("Index", new { area = "Admin" }).Error("Erro ao cadastrar usuário.");
            usuario.Senha = Hash.GerarHash(usuario.Senha);
            usuario.Adicionar(usuario);
            return RedirectToAction("Index", new { area = "Admin" }).Success("Usuário cadastrado com sucesso.");
        }

        [HttpPost]
        public ActionResult Atualizar(Usuario usuario)
        {
            var usuarioAtual = _usuario.BuscarPorId(usuario.UsuarioId);
            usuarioAtual.AlterarUsuario(usuario);
            _usuario.Atualizar(usuarioAtual);
            return RedirectToAction("Index", new { area = "Admin" }).Success("Usuário atualizado com sucesso.");
        }

        [HttpPost]
        public ActionResult Excluir(Usuario usuario)
        {
            var usuarioAtual = _usuario.BuscarPorId(usuario.UsuarioId);
            usuarioAtual.ExcluirUsuario();
            _usuario.Excluir(usuarioAtual);
            return RedirectToAction("Index", new { area = "Admin" }).Success("Usuário excluído com sucesso.");
        }

        public PartialViewResult AbrirModalAdicionar()
        {
            return PartialView("_Adicionar");
        }

        public PartialViewResult AbrirModalAtualizar(Guid usuarioId)
        {
            var usuario = _usuario.BuscarPorId(usuarioId);
            return PartialView("_Atualizar", usuario);
        }

        public PartialViewResult AbrirModalExcluir(Guid usuarioId)
        {
            var usuario = _usuario.BuscarPorId(usuarioId);
            return PartialView("_Excluir", usuario);
        }

        public ActionResult Ativo(Guid usuarioId, int pagina)
        {
            var usuarioAtual = _usuario.BuscarPorId(usuarioId);
            usuarioAtual.AtivarOuDesativar();
            _usuario.Atualizar(usuarioAtual);
            TempData["Pagina"] = pagina;
            int itensPorPagina = 5;
            var usuarios = _usuario.BuscarTodos().Where(x => !x.Excluido).ToList(); ;
            var lista = new List<Usuario>();
            lista.AddRange(usuarios);
            return PartialView("_PartialTabela", lista.ToPagedList(pagina, itensPorPagina));
        }

        public PartialViewResult BuscarUsuario(string textoDigitado, int pagina = 1)
        {
            TempData["Pagina"] = pagina;
            int itensPorPagina = 5;
            var usuarios = _usuario.BuscarTodosPorFiltro(textoDigitado).Where(x => !x.Excluido).ToList();
            var lista = new List<Usuario>();
            lista.AddRange(usuarios);
            return PartialView("_PartialTabela", lista.ToPagedList(pagina, itensPorPagina));
        }
    }
}

Gestao_Financeira/Gestao_Financeira/Areas/Admin/Views/Usuario/Index.cshtml
@{
    ViewBag.Title = "index";
}

<div class="col-md-12">
    <div class="card">
        <div class="card-header card-header-info">
            <h3 class="card-title mt-0">
                Usuários <b>
                    <a href="javascript:;" class="btn-abrirModal" data-abrirmodal="@Url.Action("AbrirModalAdicionar", "Usuario", new { area = "Admin"})" style="float: right; font-size: 17px;" data-toggle="Adicionar" title="Adicionar">
                        <i class="material-icons fa-2x">add</i>
                    </a>
                </b>
            </h3>
        </div>
        <div class="card-body carregar-itens" data-url="@Url.Action("BuscarUsuario", "Usuario", new { area = "Admin" })">
            @Html.Partial("_PartialTabela")
        </div>
    </div>
</div>

<div class="modal fade abrir-modal"></div>

@section scripts{
    @Scripts.Render("~/bundles/carregar-modal")
    @Scripts.Render("~/bundles/evento-ativo")
    @Scripts.Render("~/bundles/buscar-paginacao")
    <script>
        $(document).ready(function () {
            $(document).on("keyup", "#confirmacaosenha", function () {
                var senha = $("#Senha").val();
                var confirmacaosenha = $("#confirmacaosenha").val();
                if (senha === confirmacaosenha) {
                    $(".msg").empty();
                    $(".btn-cadastrarlogin").removeAttr("disabled");
                }
                else {
                    $(".btn-cadastrarlogin").attr("disabled", "disabled");
                    $(".msg").html("<p style='color:red;'>As senhas são diferentes</p>");
                }
            });
        });
    </script>
}

Gestao_Financeira/Gestao_Financeira/Areas/Admin/Views/Usuario/_Adicionar.cshtml
@model Gestao_Financeira.Models.Usuario

<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="TituloModalCentralizado">Adicionar Usuário</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm("Adicionar", "Usuario", FormMethod.Post, new { }))
            {
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="bmd-label-floating">Nome</label>
                            @Html.TextBoxFor(x => x.Nome, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="bmd-label-floating">Login</label>
                            @Html.TextBoxFor(x => x.Login, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="bmd-label-floating">Senha</label>
                            @Html.PasswordFor(x => x.Senha, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="bmd-label-floating">Confirmar Senha</label>
                            <input type="password" id="confirmacaosenha" class="form-control" />
                            <div class="msg"></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="bmd-label-floating">Tipo Usuário</label>
                            @Html.EnumDropDownListFor(x => x.TipoUsuario, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-info">Salvar</button>
                </div>
            }
        </div>
    </div>
</div>

Gestao_Financeira/Gestao_Financeira/Areas/Admin/Views/Usuario/_Atualizar.cshtml
@model Gestao_Financeira.Models.Usuario

<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Atualizar Usuário</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm("Atualizar", "Usuario", FormMethod.Post, new { }))
            {
                @Html.HiddenFor(x => x.UsuarioId)
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="bmd-label-floating">Nome</label>
                            @Html.TextBoxFor(x => x.Nome, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="bmd-label-floating">Login</label>
                            @Html.TextBoxFor(x => x.Login, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="bmd-label-floating">Tipo Usuário</label>
                            @Html.EnumDropDownListFor(x => x.TipoUsuario, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-info">Atualizar</button>
                </div>
            }
        </div>
    </div>
</div>

Gestao_Financeira/Gestao_Financeira/Areas/Admin/Views/Usuario/_Excluir.cshtml
@model Gestao_Financeira.Models.Usuario

<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Excluir Usuário</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="alert alert-danger">
                <span>
                    <b>Deseja excluir o cadastro?</b>
                </span>
            </div>
            @using (Html.BeginForm("Excluir", "Usuario", FormMethod.Post, new { }))
            {
                @Html.HiddenFor(x => x.UsuarioId)
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="bmd-label-floating">Nome</label>
                            @Html.TextBoxFor(x => x.Nome, new { @class = "form-control", disabled = "disabled" })
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="bmd-label-floating">Login</label>
                            @Html.TextBoxFor(x => x.Login, new { @class = "form-control", disabled = "disabled" })
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="bmd-label-floating">Tipo Usuário</label>
                            @Html.TextBoxFor(x => x.TipoUsuario, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-danger">Excluir</button>
                </div>
            }
        </div>
    </div>
</div>

Gestao_Financeira/Gestao_Financeira/Areas/Admin/Views/Usuario/_PartialTabela.cshtml
@using Gestao_Financeira.Models
@using PagedList.Mvc
@model PagedList.PagedList<Usuario>
@{
    var paginaAtual = (int)TempData["Pagina"];
}

<div class="table-responsive">
    @if (Model != null && Model.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        <b>Nome</b>
                    </th>
                    <th>
                        <b>Perfil</b>
                    </th>
                    <th>
                        <b>Ativo</b>
                    </th>
                    <th>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var usuario in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => usuario.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => usuario.TipoUsuario)
                        </td>
                        <td>
                            @if (usuario.Ativo == true)
                            {

                                <span class="badge badge-pill badge-success">Sim</span>
                            }
                            else
                            {
                                <span class="badge badge-pill badge-danger">Não</span>
                            }
                        </td>
                        <td>
                            @if (usuario.Ativo == true)
                            {
                                <button type="button" id="btn-ativo" data-ativo="@Url.Action("Ativo", "Usuario", new { usuarioId = usuario.UsuarioId })" class="btn btn-default btn-fab btn-round mr-2" data-toggle="tooltip" title="Desativar">
                                    <i class="material-icons">not_interested</i>
                                </button>
                            }
                            else
                            {
                                <button type="button" id="btn-ativo" data-ativo="@Url.Action("Ativo", "Usuario", new { usuarioId = usuario.UsuarioId })" class="btn btn-default btn-fab btn-round mr-2" data-toggle="tooltip" title="Ativar">
                                    <i class="material-icons">check_circle_outline</i>
                                </button>
                            }

                            <button type="button" id="btn-atualizar" data-abrirmodal="@Url.Action("AbrirModalAtualizar", "Usuario", new { usuarioId = usuario.UsuarioId })" class="btn btn-default btn-fab btn-round mr-2 btn-abrirModal" data-toggle="tooltip" title="Atualizar">
                                <i class="material-icons">create</i>
                            </button>
                            <button type="button" id="btn-excluir" data-abrirmodal="@Url.Action("AbrirModalExcluir", "Usuario", new { usuarioId = usuario.UsuarioId })" class="btn btn-default btn-fab btn-round btn-abrirModal" data-toggle="tooltip" title="Excluir">
                                <i class="material-icons">clear</i>
                            </button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <div class="text-center">
            <h3>Nenhuma Informação Encontrada!</h3>
        </div>
    }
    <div class="row">
        <div class="col-12 mt-5">
            <div id="pageLink" class=" float-right" data-paginaatual="@paginaAtual" style="margin-top:-20px !important;">
                @Html.PagedListPager(Model, pagina => Url.Action("BuscarUsuario", "Usuario", new { pagina = pagina }), new PagedListRenderOptions { LinkToPreviousPageFormat = "«", LinkToNextPageFormat = "»" })
            </div>
        </div>
    </div>
</div>