Gestao_Financeira/Gestao_Financeira/Models/Financeiro.cs
using Gestao_Financeira.Repository;
using Gestao_Financeira.Utils;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Gestao_Financeira.Models
{
    public class Financeiro
    {
        #region Atributos
        public Guid FinanceiroId { get; set; }
        [Required]
        public string Descricao { get; set; }
        [Required]
        public TipoFinanceiro TipoFinanceiro { get; set; }
        [Required]
        public DateTime DataLancamento { get; set; }
        public DateTime? DataAlteracao { get; set; }
        [Required]
        public decimal Valor { get; set; }
        public string ValorFormat => Valor.MarkValor();
        #endregion

        #region Relacionamentos
        [Required]
        public Guid CategoriaId { get; set; }
        public Categoria Categoria { get; set; }
        public Guid UsuarioId { get; set; }
        public Usuario Usuario { get; set; }
        #endregion

        #region Crud
        FinanceiroRepositorio _financeiroRepositories = new FinanceiroRepositorio();
        public void Adicionar(Financeiro financeiro) => _financeiroRepositories.Adicionar(financeiro, $"Adicionado financeiro {financeiro.Descricao} tipo {financeiro.TipoFinanceiro.GetDisplayName()}");
        public void Atualizar(Financeiro financeiro) => _financeiroRepositories.Atualizar(financeiro, $"Alterado financeiro {financeiro.Descricao} tipo {financeiro.TipoFinanceiro.GetDisplayName()}");
        public Financeiro BuscarPorId(Guid financeiroId) => _financeiroRepositories.BuscarPorId(financeiroId);
        public IEnumerable<Financeiro> BuscarTodos(Guid usuarioId) => _financeiroRepositories.BuscarTodos(usuarioId);
        public IEnumerable<Financeiro> BuscarTodosPorAnoMes(Guid usuarioId, int ano, int? mes) => _financeiroRepositories.BuscarTodosPorAnoMes(usuarioId, ano, mes);
        public IEnumerable<Financeiro> BuscarTodosPorFiltro(string textoDigitado, Guid categoria, string tipo, int data, int ano, Guid usuarioId) => _financeiroRepositories.BuscarTodosPorFiltro(textoDigitado, categoria, tipo, data, ano, usuarioId);

        #endregion

        #region Métodos
        public void EditarFinanceiro(string valor)
        {
            DataAlteracao = DateTimeFormatRO.GetDateTimeFusoRondonia(DateTime.UtcNow);
            Valor = Convert.ToDecimal(valor);
        }
        #endregion
    }
}

Gestao_Financeira/Gestao_Financeira/Areas/User/Controllers/CategoriaController.cs
using Gestao_Financeira.Helpers;
using Gestao_Financeira.Models;
using Gestao_Financeira.Utils;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Gestao_Financeira.Areas.User.Controllers
{
    [Permissoes(Roles = "Usuario")]
    public class CategoriaController : Controller
    {

        private readonly Categoria _categoria;

        public CategoriaController()
        {
            _categoria = new Categoria();
        }

        public ActionResult Index(int pagina = 1)
        {
            try
            {
                if (Account.UsuarioId == Guid.Empty)
                    return RedirectToAction("Index", "Home");

                TempData["Pagina"] = pagina;
                int itensPorPagina = 5;
                var categorias = _categoria.BuscarTodos(Account.UsuarioId).Where(x => !x.Excluido).ToList();
                var lista = new List<Categoria>();
                lista.AddRange(categorias);
                return View(lista.ToPagedList(pagina, itensPorPagina));
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult Adicionar(Categoria categoria)
        {
            if (!ModelState.IsValid) return RedirectToAction("Index", new { area = "User" }).Error("Erro ao cadastrar categoria.");
            categoria.Adicionar(categoria);
            return RedirectToAction("Index", new { area = "User" }).Success("Categoria cadastrado com sucesso.");
        }

        [HttpPost]
        public ActionResult Atualizar(Categoria categoria)
        {
            var categoriaAtual = _categoria.BuscarPorId(categoria.CategoriaId);
            categoriaAtual.AlterarCategoria(categoria);
            _categoria.Atualizar(categoriaAtual);
            return RedirectToAction("Index", new { area = "User" }).Success("Categoria atualizado com sucesso.");
        }

        [HttpPost]
        public ActionResult Excluir(Categoria categoria)
        {
            var categoriaAtual = _categoria.BuscarPorId(categoria.CategoriaId);
            categoriaAtual.ExcluirCategoria();
            _categoria.Excluir(categoriaAtual);
            return RedirectToAction("Index", new { area = "User" }).Success("Categoria excluído com sucesso.");
        }

        public PartialViewResult AbrirModalAdicionar()
        {
            return PartialView("_Adicionar");
        }

        public PartialViewResult AbrirModalAtualizar(Guid categoriaId)
        {
            var categoria = _categoria.BuscarPorId(categoriaId);
            return PartialView("_Atualizar", categoria);
        }

        public PartialViewResult AbrirModalExcluir(Guid categoriaId)
        {
            var categoria = _categoria.BuscarPorId(categoriaId);
            return PartialView("_Excluir", categoria);
        }

        public ActionResult Ativo(Guid categoriaId, int pagina)
        {
            var categoriaAtual = _categoria.BuscarPorId(categoriaId);
            categoriaAtual.AtivarOuDesativar();
            _categoria.Atualizar(categoriaAtual);
            TempData["Pagina"] = pagina;
            int itensPorPagina = 5;
            var categorias = _categoria.BuscarTodos(Account.UsuarioId).Where(x => !x.Excluido).ToList(); ;
            var lista = new List<Categoria>();
            lista.AddRange(categorias);
            return PartialView("_PartialTabela", lista.ToPagedList(pagina, itensPorPagina));
        }

        public PartialViewResult BuscarCategoria(string textoDigitado, int pagina = 1)
        {
            TempData["Pagina"] = pagina;
            int itensPorPagina = 5;
            var categorias = _categoria.BuscarTodosPorFiltro(textoDigitado, Account.UsuarioId).Where(x => !x.Excluido).ToList();
            var lista = new List<Categoria>();
            lista.AddRange(categorias);
            return PartialView("_PartialTabela", lista.ToPagedList(pagina, itensPorPagina));
        }

        public JsonResult AdicionarPorFinanceiro(string nome)
        {
            var categoria = new Categoria{ Nome = nome };
            _categoria.Adicionar(categoria);
            return Json(_categoria.BuscarTodos(Account.UsuarioId).Where(x => !x.Excluido).Select(x => $"<option value='{x.CategoriaId}'>{x.Nome}</option>"), JsonRequestBehavior.AllowGet);
        }
    }
}

Gestao_Financeira/Gestao_Financeira/Areas/User/Controllers/FinanceiroController.cs
using Gestao_Financeira.Helpers;
using Gestao_Financeira.Models;
using Gestao_Financeira.Utils;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Gestao_Financeira.Areas.User.Controllers
{
    [Permissoes(Roles = "Usuario")]
    public class FinanceiroController : Controller
    {

        private readonly Financeiro _financeiro;
        private readonly Categoria _categoria;

        public FinanceiroController()
        {
            _financeiro = new Financeiro();
            _categoria = new Categoria();
        }

        public ActionResult Index(int pagina = 1)
        {
            try
            {
                if (Account.UsuarioId == Guid.Empty)
                    return RedirectToAction("Index", "Home");

                var listaDeAnos = _financeiro.BuscarTodos(Account.UsuarioId).GroupBy(x => x.DataLancamento.Year).OrderBy(x => x.Key).ToList();

                ViewBag.SelectAnos = new SelectList(listaDeAnos, "Key", "Key");
                ViewBag.Categorias = new SelectList(_categoria.BuscarTodos(Account.UsuarioId).Where(x => !x.Excluido && x.Ativo), "CategoriaId", "Nome");
                TempData["Pagina"] = pagina;
                int itensPorPagina = 5;
                var financeiros = _financeiro.BuscarTodos(Account.UsuarioId).ToList();
                var lista = new List<Financeiro>();
                lista.AddRange(financeiros);
                return View(lista.ToPagedList(pagina, itensPorPagina));
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult Adicionar(Financeiro financeiro, string valor)
        {
            if (string.IsNullOrEmpty(financeiro.Descricao) || string.IsNullOrEmpty(valor) || financeiro.TipoFinanceiro == 0)
                return View().Error("Erro ao adicionar financeiro");
            financeiro.DataLancamento = DateTimeFormatRO.GetDateTimeFusoRondonia(financeiro.DataLancamento.AddDays(1));
            financeiro.Valor = Convert.ToDecimal(valor);
            financeiro.Adicionar(financeiro);
            return RedirectToAction("Index", new { area = "User" }).Success("Financeiro cadastrado com sucesso.");
        }

        [HttpPost]
        public ActionResult Atualizar(Financeiro financeiro, string valor)
        {
            if (string.IsNullOrEmpty(financeiro.Descricao) || string.IsNullOrEmpty(valor) || financeiro.TipoFinanceiro == 0)
                return View().Error("Erro ao atualizar financeiro");
            financeiro.EditarFinanceiro(valor);
            _financeiro.Atualizar(financeiro);
            return RedirectToAction("Index", new { area = "User" }).Success("Financeiro atualizado com sucesso.");
        }

        public PartialViewResult AbrirModalAdicionar()
        {
            ViewBag.Categorias = new SelectList(_categoria.BuscarTodos(Account.UsuarioId).Where(x => !x.Excluido && x.Ativo), "CategoriaId", "Nome");
            return PartialView("_Adicionar");
        }

        public PartialViewResult AbrirModalAtualizar(Guid financeiroId)
        {
            ViewBag.Categorias = new SelectList(_categoria.BuscarTodos(Account.UsuarioId).Where(x => !x.Excluido && x.Ativo), "CategoriaId", "Nome");
            var financeiro = _financeiro.BuscarPorId(financeiroId);
            return PartialView("_Atualizar", financeiro);
        }

        public PartialViewResult AbrirModalDetalhes(Guid financeiroId)
        {
            return PartialView("_Detalhes", _financeiro.BuscarPorId(financeiroId));
        }

        public PartialViewResult BuscarFinanceiro(string textoDigitado, string categoria, string tipo = "", int data = 0, int ano = 0, int pagina = 1)
        {
            ano = ano != 0 ? ano : DateTime.UtcNow.Year;
            var itensPorPagina = 5;
            var categoriaId = string.IsNullOrEmpty(categoria) ? Guid.Empty : Guid.Parse(categoria);
            TempData["Pagina"] = pagina;
            var financeiros = _financeiro.BuscarTodosPorFiltro(textoDigitado, categoriaId, tipo, data, ano, Account.UsuarioId);
            var lista = new List<Financeiro>();
            lista.AddRange(financeiros);
            return PartialView("_PartialTabela", lista.ToPagedList(pagina, itensPorPagina));
        }
    }
}

Gestao_Financeira/Gestao_Financeira/Areas/User/Views/Financeiro/Index.cshtml
@{
    ViewBag.Title = "index";
}

    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-info">
                <h3 class="card-title mt-0">
                    Financeiros <b>
                        <a href="javascript:;" class="btn-abrirModal" data-abrirmodal="@Url.Action("AbrirModalAdicionar", "Financeiro", new { area = "User"})" style="float: right; font-size: 17px;" data-toggle="Adicionar" title="Adicionar">
                            <i class="material-icons fa-2x">add</i>
                        </a>
                    </b>
                </h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4">
                        <input class="form-control float-right" id="input-pesquisa" placeholder="Pesquisar por descrição" />
                    </div>
                    <div class="input-group col-md-3">
                        <select class="form-control" id="fin-cate" required>
                            <option value="" selected>Pesquisar por Categoria</option>
                            @foreach (var item in (SelectList)ViewBag.Categorias)
                            {
                                <option value="@item.Value">@item.Text</option>
                            }
                        </select>
                        <i class="material-icons select-tabela">arrow_drop_down</i>
                    </div>
                    <div class="input-group col-md-2">
                        <select class="form-control" id="fin-tipo" required>
                            <option value="" selected>Pesquisar por tipo</option>
                            <option value="1">Entrada</option>
                            <option value="2">Saída</option>
                        </select>
                        <i class="material-icons select-tabela">arrow_drop_down</i>
                    </div>
                    <div class="input-group col-md-2">
                        <select class="form-control" id="fin-data" required>
                            <option value="" selected>Pesquisar por Mês</option>
                            <option value="1">Janeiro</option>
                            <option value="2">Fevereiro</option>
                            <option value="3">Março</option>
                            <option value="4">Abril</option>
                            <option value="5">Maio</option>
                            <option value="6">Junho</option>
                            <option value="7">Julho</option>
                            <option value="8">Agosto</option>
                            <option value="9">Setembro</option>
                            <option value="10">Outubro</option>
                            <option value="11">Novembro</option>
                            <option value="12">Dezembro</option>
                        </select>
                        <i class="material-icons select-tabela">arrow_drop_down</i>
                    </div>
                    <div class="input-group col-md-1">
                        <select class="form-control" id="fin-ano" required data-ano="@DateTime.UtcNow.Year">
                            <option value="" disabled selected hidden>@DateTime.UtcNow.Year</option>
                            @foreach (var item in (SelectList)ViewBag.SelectAnos)
                            {
                                <option value="@item.Value">@item.Text</option>
                            }
                        </select>
                        <i class="material-icons select-tabela">arrow_drop_down</i>
                    </div>
                </div>
                <div class="carregar-itens mt-5" data-url="@Url.Action("BuscarFinanceiro", "Financeiro", new { area = "User" })">
                    @Html.Partial("_PartialTabela")
                </div>
            </div>
        </div>
    </div>

<div class="modal fade abrir-modal"></div>

@section scripts{
    @Scripts.Render("~/bundles/carregar-modal")
    @Scripts.Render("~/bundles/evento-ativo")
    @Scripts.Render("~/bundles/filtro-financeiro")

<script>
    $(document).on("click", "#add-categoria", function () {

        swal.fire({
            title: 'Adicionar categoria',
            input: 'text',
            inputPlaceholder: 'Digite o nome da categoria',
            showCancelButton: true,
            confirmButtonText: 'Salvar',
            inputValidator: (value) => {
                if (!value) {
                    return 'Nome da categoria é obrigatório'
                }
            }
        }).then((data) => {
            if (data.value !== undefined && data.value !== "") {
                $(".modal-content").LoadingOverlay("show");
                var url = $("#add-categoria").data("url");
                $.ajax({
                    url: url,
                    data: { nome: data.value },
                    success: function (result) {
                        $("#CategoriaId").empty();
                        $("#CategoriaId").append("<option value></option>");
                        $("#CategoriaId").append(result);
                        Lobibox.notify('success', { position: 'top right', sound: '', delay: 3000, msg: 'Categoria cadastrada com sucesso', title: 'Sucesso', icon: 'smile icon' });
                        $(".modal-content").LoadingOverlay("hide");
                    },
                    error: function () {
                        swal.fire('Erro ao cadastrar categoria');
                        $(".modal-content").LoadingOverlay("hide");
                    }
                });
            }
        });




    });
</script>
}

Gestao_Financeira/Gestao_Financeira/Areas/User/Views/Financeiro/_Adicionar.cshtml
@model Gestao_Financeira.Models.Financeiro

<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="TituloModalCentralizado">Adicionar Financeiro</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm("Adicionar", "Financeiro", FormMethod.Post, new { }))
            {
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="bmd-label-floating">Descrição</label>
                            @Html.TextBoxFor(x => x.Descricao, new { @class = "form-control", required = "required" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="bmd-label-floating">Tipo do Financeiro</label>
                            @Html.EnumDropDownListFor(x => x.TipoFinanceiro, new { @class = "form-control", required = "required" })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="bmd-label-floating">Data Lançamento</label>
                            @Html.TextBoxFor(x => x.DataLancamento, new { @class = "form-control", @type = "date", @Value = DateTime.UtcNow.ToString("yyy-MM-dd"), required = "required" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="bmd-label-floating">Categoria</label>
                            <div class="input-group">
                                @Html.DropDownListFor(model => model.CategoriaId, (SelectList)ViewBag.Categorias, "", new { @class = "form-control" })
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-fab btn-round btn-info btn-sm" id="add-categoria" data-url="@Url.Action("AdicionarPorFinanceiro", "Categoria", new { area = "User" })">
                                        <i class="material-icons">add</i>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="bmd-label-floating">Valor</label>
                            <input type="text" name="valor" id="valor" class="form-control" required />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-info">Salvar</button>
                </div>
            }
        </div>
    </div>
</div>

Gestao_Financeira/Gestao_Financeira/Areas/User/Views/Financeiro/_Atualizar.cshtml
@model Gestao_Financeira.Models.Financeiro
@{ 
    var data = Model.DataLancamento.ToString("yyyy-MM-dd");
}
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="TituloModalCentralizado">Atualizar Financeiro</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm("Atualizar", "Financeiro", FormMethod.Post, new { }))
            {
                @Html.HiddenFor(x => x.FinanceiroId)
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="bmd-label-floating">Descrição</label>
                            @Html.TextBoxFor(x => x.Descricao, new { @class = "form-control", required = "required" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="bmd-label-floating">Tipo do Financeiro</label>
                            @Html.EnumDropDownListFor(x => x.TipoFinanceiro, new { @class = "form-control", required = "required" })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="bmd-label-floating">Data Lançamento</label>
                            @Html.TextBoxFor(x => x.DataLancamento, new { @class = "form-control", required = "required", @type = "date", @Value = data })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="bmd-label-floating">Categoria</label>
                            <div class="input-group">
                                @Html.DropDownListFor(model => model.CategoriaId, (SelectList)ViewBag.Categorias, "", new { @class = "form-control", required = "required" })
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-fab btn-round btn-info btn-sm" id="add-categoria" data-url="@Url.Action("AdicionarPorFinanceiro", "Categoria", new { area = "User" })">
                                        <i class="material-icons">add</i>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="bmd-label-floating">Valor</label>
                            <input type="text" name="valor" id="valor" value="@Model.Valor" class="form-control" required />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-info">Atualizar</button>
                </div>
            }
        </div>
    </div>
</div>

Gestao_Financeira/Gestao_Financeira/Areas/User/Views/Financeiro/_Detalhes.cshtml
@model Gestao_Financeira.Models.Financeiro

<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="TituloModalCentralizado">Detalhes Financeiro</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="bmd-label-floating">Descrição</label>
                        @Html.TextBoxFor(x => x.Descricao, new { @class = "form-control", disabled = "disabled" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="bmd-label-floating">Tipo do Financeiro</label>
                        @Html.TextBoxFor(x => x.TipoFinanceiro, new { @class = "form-control", disabled = "disabled" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="bmd-label-floating">Data Lançamento</label>
                        @Html.TextBoxFor(x => x.DataLancamento, new { @class = "form-control data", disabled = "disabled" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="bmd-label-floating">Categoria</label>
                        @Html.TextBoxFor(model => model.Categoria.Nome, new { @class = "form-control", disabled = "disabled" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="bmd-label-floating">Valor</label>
                        @Html.TextBoxFor(x => x.Valor, new { @class = "form-control money", disabled = "disabled" })
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

Gestao_Financeira/Gestao_Financeira/Areas/User/Views/Financeiro/_PartialTabela.cshtml
@using Gestao_Financeira.Models
@using PagedList.Mvc
@model PagedList.PagedList<Financeiro>
@{
    var paginaAtual = (int)TempData["Pagina"];
}

<div class="table-responsive">
    @if (Model != null && Model.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th>Descrição</th>
                    <th>Categoria</th>
                    <th>Tipo</th>
                    <th>Data</th>
                    <th>Valor</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var financeiro in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => financeiro.Descricao)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => financeiro.Categoria.Nome)
                    </td>
                    <td>
                        @if (financeiro.TipoFinanceiro == TipoFinanceiro.Entrada)
                        {
                        <span class="badge badge-pill badge-success">Entrada</span>
                        }
                        else
                        {
                            <span class="badge badge-pill badge-danger">Saída</span>
                        }
                    </td>
                    <td class="data">
                        @financeiro.DataLancamento.ToString("dd/MM/yyyy")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => financeiro.ValorFormat)
                    </td>
                    <td>
                        <button type="button" id="btn-atualizar" data-abrirmodal="@Url.Action("AbrirModalAtualizar", "Financeiro", new { financeiroId = financeiro.FinanceiroId })" class="btn btn-default btn-fab btn-round mr-2 btn-abrirModal" data-toggle="tooltip" title="Atualizar">
                            <i class="material-icons">create</i>
                        </button>
                        <button type="button" id="btn-detalhes" data-abrirmodal="@Url.Action("AbrirModalDetalhes", "Financeiro", new { financeiroId = financeiro.FinanceiroId })" class="btn btn-default btn-fab btn-round btn-abrirModal" data-toggle="tooltip" data-placement="top" title="Detalhes">
                            <i class="material-icons">list</i>
                        </button>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <div class="text-center">
            <h3>Nenhuma Informação Encontrada!</h3>
        </div>
    }
    <div class="row">
        <div class="col-12 mt-3">
            <div id="pageLink" class="float-right" data-paginaatual="@paginaAtual" style="margin-top:-20px !important;">
                @Html.PagedListPager(Model, pagina => Url.Action("BuscarFinanceiro", "Financeiro", new { area = "User", pagina = pagina }), new PagedListRenderOptions { LinkToPreviousPageFormat = "«", LinkToNextPageFormat = "»" })
            </div>
        </div>
    </div>
</div>