Gestao_Financeira/Gestao_Financeira/Areas/User/Controllers/ConfiguracaoController.cs
using Gestao_Financeira.Helpers;
using Gestao_Financeira.Models;
using Gestao_Financeira.Utils;
using System;
using System.Web.Mvc;

namespace Gestao_Financeira.Areas.User.Controllers
{
    [Permissoes(Roles = "Usuario")]
    public class ConfiguracaoController : Controller
    {
        private readonly Usuario _usuario;

        public ConfiguracaoController()
        {
            _usuario = new Usuario();
        }

        public ActionResult AlterarDados()
        {
            try
            {
                if (Account.UsuarioId == Guid.Empty)
                    return RedirectToAction("Index", "Home");

                return View(_usuario.BuscarPorId(Account.UsuarioId));
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult AlterarDados(Usuario usuario)
        {
            var usuarioAtual = _usuario.BuscarPorId(usuario.UsuarioId);
            usuarioAtual.AlterarUsuario(usuario);
            _usuario.Atualizar(usuarioAtual);
            return RedirectToAction("Index", "Dashboard", new { area = "User" }).Success();
        }
    }
}

Gestao_Financeira/Gestao_Financeira/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta http-equiv="content-security-policy|content-type|default-style|refresh">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Eloenay Pereira">
    <title>Gestão Financeira</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    @Styles.Render("~/Content/layout-externo")
    @Styles.Render("~/Content/lobibox")
</head>
<body>
    @Html.Partial("_MenuTopoExterno")

    <main class="py-4 main">
        @RenderBody()
    </main>

    @Scripts.Render("~/bundles/layout-externo")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/lobibox")
    @Scripts.Render("~/bundles/loading")
    @RenderSection("scripts", required: false)
    @Html.Partial("_Toastr")
</body>
</html>

Gestao_Financeira/Gestao_Financeira/Views/Shared/_LayoutInterno.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta http-equiv="content-security-policy|content-type|default-style|refresh">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Eloenay Pereira">
    <title>Gestão Financeira</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    @Styles.Render("~/Content/layout-interno")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)
    @Styles.Render("~/Content/lobibox")
    @Styles.Render("~/Content/sweetalert2")
</head>
<body>
    <div class="wrapper">
        <div class="sidebar" data-color="azure" data-background-color="white" data-image="#">
            @RenderSection("Menu", true)
        </div>
        <div class="main-panel">
            @Html.Partial("_MenuTopoInterno")
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/layout-interno")
    @Scripts.Render("~/bundles/lobibox")
    @Scripts.Render("~/bundles/sweetalert2")
    @Scripts.Render("~/bundles/mask")
    @Scripts.Render("~/bundles/loading")

    @RenderSection("scripts", required: false)
    @Html.Partial("_Toastr")
    <script>
        $(document).ready(function () {
            $(document).on("click", "button[type = 'submit']", function () {
                $("body").LoadingOverlay("show");
            });
            $(document).on("click", "a.nav-link", function () {
                $("body").LoadingOverlay("show");
            });
            $(document).on("click", ".btn-abrirModal", function () {
                $("body").LoadingOverlay("show");
            });
            $(document).on("click", ".dropdown-item", function () {
                $("body").LoadingOverlay("show");
            });
        });
    </script>
</body>
</html>

Gestao_Financeira/Gestao_Financeira/Views/Shared/_MenuTopoExterno.cshtml
<nav class="navbar navbar-expand-md navbar-light">
    <div class="container">
        <a class="navbar-brand" href="#">
            Gestão Financeira
        </a>
        <a class="navbar-toggler" href="javascript:;" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="btn-abrirModal btn btn-outline-primary" href="javascript:;" data-toggle="modal" data-target=".abrir-modal" data-abrirmodal="@Url.Action("AbrirModalLogin", "Home", new { })"><i class="fa fa-hand-o-right">&nbsp;</i> Acessar conta</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

Gestao_Financeira/Gestao_Financeira/Views/Shared/_MenuTopoInterno.cshtml
@using Gestao_Financeira.Utils
@{
    string tipo = Account.Roles == "Usuario" ? "User" : "Admin";
}
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <a class="navbar-brand" href="javascript:;">Gestão Financeira<div class="ripple-container"></div></a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link-user" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">person</i>
                        <b class="">
                            @User.Identity.Name
                        </b>
                        <div class="ripple-container"></div>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right navbar-form" aria-labelledby="navbarDropdownProfile">
                        <a class="dropdown-item" href="@Url.Action("AlterarDados","Configuracao", new { area = tipo})">Alterar Dados</a>
                        <a class="dropdown-item" href="@Url.Action("Logout","Home", new { area = ""})">Sair</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

Gestao_Financeira/Gestao_Financeira/Views/Shared/_Toastr.cshtml
@using Gestao_Financeira.Helpers
@{
    var alerts = TempData.ContainsKey("Message") ? (List<Alert>)TempData["Message"] : new List<Alert>();
    if (alerts.Any())
    {
    <script>
            @{
               foreach (var item in alerts)
               {
                   if (item.AlertStyle == "success")
                   {
                       @:Lobibox.notify('success', { position: 'top right', sound: '', delay: 3000, msg: '@item.Message', title: 'Sucesso', icon: 'smile icon' });
                   }
                   else if (item.AlertStyle == "error")
                   {
                       @:Lobibox.notify('error', { position: 'top right', sound: '', delay: 3000, msg: '@item.Message', title: 'Erro', icon: 'frown icon' });
                   }
                   else if (item.AlertStyle == "warning")
                   {
                       @:Lobibox.notify('warning', { position: 'top right', sound: '', delay: 3000, msg: '@item.Message', title: 'Alerta', icon: 'warning icon' });
                   }
                   else if (item.AlertStyle == "info")
                   {
                       @:Lobibox.notify('info', { position: 'top right', sound: '', delay: 3000, msg: '@item.Message', title: 'Informação', icon: 'info circleicon' });
                   }
               }
           }
    </script>
    }
}